[package]
name = "backup-applicator"
version = "0.1.0"
authors = ["covers1624 <laughlan.cov@internode.on.net>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
java-properties = "1.3.0"
zip = "0.5.8"
chrono = { version = "0.4.19", features = ["unstable-locales"] }